### ISSUE TITLE
[BUG] Rebase Main Branch w/ Refactors from upstream core

### ISSUE THREAD

**Issue by nknize** [opensearch-project/anomaly-detection#970]
**What is the bug?**
Build fails with some latest namespace and library refactoring from core (e.g., [#9005](https://github.com/opensearch-project/OpenSearch/pull/9005)). This was caught by the [compatibility checker](https://github.com/opensearch-project/OpenSearch/actions/runs/5742101583/job/15563536027?pr=9073#step:3:1418) on [#9073](https://github.com/opensearch-project/OpenSearch/pull/9073).

**How can one reproduce the bug?**
Build with latest SNAPSHOT version of core

**What is the expected behavior?**
Passing build

**Do you have any screenshots?**
```
/tmp/groovy-generated-tmpdir-2783003216922734666/src/main/java/org/opensearch/ad/cluster/ClusterManagerEventListener.java:23: error: package org.opensearch.common.component does not exist

import org.opensearch.common.component.LifecycleListener;
```

**Do you have any additional context?**
[#5910](https://github.com/opensearch-project/OpenSearch/issues/5910)

**Comment by kaituo** [comment]
The build failure is fixed in https://github.com/opensearch-project/anomaly-detection/pull/969 waiting for one more approval (cc @amitgalitz )

**Comment by kaituo** [comment]
The build failures due to LifecycleListener are fixed in https://github.com/opensearch-project/anomaly-detection/pull/969
